# Theme
remote_theme: 'epidrome/cover-card'

# Title and tag line
title: '<font color="DarkRed">Christine Cai</font>'
description: 'Ph.D. Candidate in Economics at Princeton University'

# Images
avatar: 'avatar.jpg'
background: 'background.jpg'
favicon: 'favicon.ico'

# Online profiles
#dribbble: 'mydribbble'
#facebook: 'myfacebook'
twitter: 'https://twitter.com/Christine_Cai27'
linkedin: 'https://www.linkedin.com/in/christinecai'
#instagram: 'myinsta'
#pinterest: 'mypinterest'
#youtube: 'myyoutube'
github-user: 'https://github.com/christinecai/christinecai.github.io'
#gitlab-user: ''
#codepen: ''
#steam: ''
#soundcloud: ''
#lastfm: ''
#stack-overflow: ''
#reddit: ''
#rubygems: ''
#medium:  ''
#tumblr: 'mytumblr'
#weibo: 'myweibo'
#vk: 'myvk'
#blog_url: 'myblog.blog.com'
email: 'christine.cai@princeton.edu'
#messenger: 'myfbchat'
orcid: 'https://orcid.org/0000-0002-6978-7644'

social-links-order: [email, twitter, linkedin, github-user, orcid]

# Advanced settings
plugins:
  - jekyll-remote-theme

# Yaml manifest of supported social links
# Requirements:
# `name`
#     - plain-text name of the site (e.g. twitter)
#     - **mandatory**
# `url-pattern`
#     - site URL pattern containing a placeholder string (e.g. twitter.com/__USERNAME__)
#     - placeholder will be replaced by username or value specified in _config.yml (e.g. twitter.com/mytwitter)
#     - **mandatory**
# `url-scheme`
#     - the hardcoded URI/URN url-scheme (e.g. https://)
#     - can be one of: ['https://', 'http://', 'mailto:']
#     - defaults to '//'
#     - **optional**
# `icon-class`
#     - the font awesome icon class names
#     - font-awesome free and supports `fas` (solid) and `fab` (brands) styles
#     - defaults to `fab` style and uses value of `name` attribute (e.g. fab fa-2x fa-twitter)
#     - **optional**
social-links:
  - name: twitter
    url-pattern: twitter.com/Christine_Cai27

  - name: linkedin
    url-pattern: linkedin.com/in/christinecai
    
  - name: orcid
    url-pattern: https://orcid.org/0000-0002-6978-7644

  - name: github-user
    url-pattern: github.com/christinecai/christinecai.github.io
    icon-class: fab fa-2x fa-github

  - name: email
    url-scheme: 'mailto:'
    url-pattern: 'christine.cai@princeton.edu'
    icon-class: far fa-2x fa-envelope-open
